cargo-features = ["strip"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
serde = "1.0.189"
serde_json = "1.0.107"
swc_core = { version = "0.86.1", features = ["common"] }
anyhow = "1.0.75"
napi-derive = "2.13.0"

[profile.release]
lto = true
