cargo-features = ["strip"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
serde = "1.0.157"
serde_json = "1.0.94"
swc_core = { version = "0.69.11", features = ["common"] }
anyhow = "1.0.70"
napi-derive = "2.11.2"
unicode-segmentation="1.10.1"

[profile.release]
lto = true
