[package]
name = "core"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
node = ["napi", "napi-derive"]

[dependencies]
anyhow = { workspaces = true }
serde_json = { workspace = true }
serde = { workspace = true }
swc_common = { version = "0.33.8" }
swc_ecmascript = { version = "0.236.43", features = ["parser", "visit"] }
rayon = "1.8.0"
lazy_static = "1.4.0"
napi = { workspace = true, optional = true }
napi-derive = { workspace = true, optional = true }
