[package]
name = "binding_wasm"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
core = { path = "../core", features = ["wasm"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { version = "0.4.38" }
js-sys = { version = "0.3.65" }
serde-wasm-bindgen = "0.6.1"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
